import { Doctor } from '../types';

export const NEARBY_DOCTORS: Doctor[] = [
  {
    id: 'doc-1',
    name: 'Dr. Rajesh V. Sharma, MS, FICO',
    age: 52,
    experience: 25,
    qualification: 'MBBS, MS (Ophthalmology, AIIMS New Delhi), FICO (UK), Fellowship in Vitreoretina (LVPEI)',
    specialty: 'Senior Vitreoretinal Consultant & Macular Specialist',
    clinicName: 'Aravind Advanced Retina & Vitreous Center',
    clinicNumber: '+91 98201 44521',
    address: '42 Kasturba Gandhi Marg, Connaught Place, New Delhi',
    distance: 1.2,
    rating: 4.96,
    reviewCount: 428,
    consultationFee: '₹1,200 (CGHS / Cashless TPA Accepted)',
    availability: 'Available Today • 9:00 AM - 4:30 PM',
    acceptingReferrals: true,
    avatarColor: 'bg-teal-600',
    expertiseTags: ['Diabetic Retinopathy', 'Panretinal Photocoagulation', 'Micro-incision Vitrectomy', 'Laser Surgery']
  },
  {
    id: 'doc-2',
    name: 'Dr. Priya Nambiar, MBBS, MS, FRCS',
    age: 42,
    experience: 16,
    qualification: 'MBBS, MS (Ophthalmology, CMC Vellore), FRCS (Glasgow), Fellowship in Retina (Sankara Nethralaya)',
    specialty: 'Vitreoretinal Surgeon & Diabetic Eye Specialist',
    clinicName: 'Sankara Nethralaya Specialty Retina Suite',
    clinicNumber: '+91 80 4123 7890',
    address: '18 College Road, Nungambakkam, Chennai',
    distance: 2.4,
    rating: 4.94,
    reviewCount: 365,
    consultationFee: '₹1,000 (Insurance Accepted)',
    availability: 'Available Today • 10:00 AM - 5:30 PM',
    acceptingReferrals: true,
    avatarColor: 'bg-indigo-600',
    expertiseTags: ['Severe NPDR', 'Anti-VEGF Therapy', 'Diabetic Macular Edema', 'Fundus Angiography']
  },
  {
    id: 'doc-3',
    name: 'Dr. Arvind Swaminathan, MD, DNB',
    age: 48,
    experience: 22,
    qualification: 'MBBS, MD (Ophthalmology, PGI Chandigarh), DNB, Vitreoretinal Fellowship (Aravind Eye Care System)',
    specialty: 'Vitreoretinal Microsurgery & Proliferative DR Expert',
    clinicName: 'Netralaya Super Specialty Eye Institute',
    clinicNumber: '+91 22 2845 9912',
    address: '302 High Street Corporate Wing, Worli, Mumbai',
    distance: 3.5,
    rating: 4.91,
    reviewCount: 512,
    consultationFee: '₹1,500 (Corporate & Private Panels)',
    availability: 'Next Slot: Tomorrow at 10:15 AM',
    acceptingReferrals: true,
    avatarColor: 'bg-sky-600',
    expertiseTags: ['Proliferative DR (PDR)', 'Vitrectomy 25G/27G', 'Tractional Retinal Detachment', 'Endolaser']
  },
  {
    id: 'doc-4',
    name: 'Dr. Sunita Kulkarni, MS, FLVPEI',
    age: 40,
    experience: 14,
    qualification: 'MBBS, MS (Ophthalmology, KEM Hospital Mumbai), Fellowship in Vitreoretina (L.V. Prasad Eye Institute)',
    specialty: 'Medical Retina, Uveitis & Ophthalmic Microvascular Imaging',
    clinicName: 'Apollo Sugar & Retina Clinic',
    clinicNumber: '+91 40 2360 7777',
    address: 'Road No. 72, Jubilee Hills, Hyderabad',
    distance: 4.8,
    rating: 4.89,
    reviewCount: 284,
    consultationFee: '₹900 (All Major TPAs Covered)',
    availability: 'Available Today • 1:00 PM - 6:00 PM',
    acceptingReferrals: true,
    avatarColor: 'bg-emerald-600',
    expertiseTags: ['Early DR Detection', 'OCT-Angiography', 'Macular Ischemia', 'Tele-Retinopathy']
  },
  {
    id: 'doc-5',
    name: 'Dr. Vikramaditya Reddy, MS, FACS',
    age: 55,
    experience: 28,
    qualification: 'MBBS, MS (Ophthalmology), FACS, Fellowship in Vitreoretinal Surgery (Narayana Nethralaya)',
    specialty: 'Senior Vitreoretinal Surgeon & Ophthalmic Trauma',
    clinicName: 'Narayana Nethralaya Diabetic Retina Center',
    clinicNumber: '+91 80 6612 1400',
    address: '121/C Chord Road, Rajajinagar 1st R Block, Bengaluru',
    distance: 6.2,
    rating: 4.87,
    reviewCount: 630,
    consultationFee: '₹1,100 (ECHS / Ayushman / TPA)',
    availability: 'Available Thursday • 8:30 AM - 3:00 PM',
    acceptingReferrals: true,
    avatarColor: 'bg-amber-600',
    expertiseTags: ['Complex Retinal Detachment', 'Vitreous Hemorrhage', 'PDR Laser', 'Scleral Buckling']
  },
  {
    id: 'doc-6',
    name: 'Dr. Meenakshi Sundaram, MD, FICO',
    age: 38,
    experience: 12,
    qualification: 'MBBS, MD (Ophthalmology, AIIMS), FICO (UK), Fellowship in Retinal Lasers & Angiography',
    specialty: 'Comprehensive Ophthalmology & Diabetic Retinopathy',
    clinicName: 'Max Vision Diabetic Eye Care Wing',
    clinicNumber: '+91 11 4055 4055',
    address: '1 Press Enclave Marg, Saket, New Delhi',
    distance: 8.5,
    rating: 4.82,
    reviewCount: 198,
    consultationFee: '₹800 (Govt & Commercial Panels)',
    availability: 'Available Friday • 9:00 AM - 2:00 PM',
    acceptingReferrals: false,
    avatarColor: 'bg-rose-600',
    expertiseTags: ['Diabetic Cataract', 'Retinal Screening', 'Fluorescein Angiography', 'Argon Laser']
  }
];
